# Generated by Django 4.2.30 on 2026-04-30 04:41

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('director', 'Director'), ('docente', 'Docente')], default='docente', max_length=20, verbose_name='Rol')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Foto de perfil')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActividadInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha', models.DateField(verbose_name='Fecha de actividad')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('lugar', models.CharField(blank=True, max_length=200, verbose_name='Lugar')),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Presupuesto (S/)')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('responsables', models.ManyToManyField(limit_choices_to={'role': 'docente'}, related_name='actividades_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsables')),
            ],
            options={
                'verbose_name': 'Actividad Institucional',
                'verbose_name_plural': 'Actividades Institucionales',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del lugar')),
                ('ubicacion', models.CharField(max_length=300, verbose_name='Ubicación/Dirección')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Distancia (km)')),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('nivel', models.CharField(blank=True, max_length=50, verbose_name='Nivel')),
                ('turno', models.CharField(choices=[('mañana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], default='mañana', max_length=20, verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PropuestaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título de la propuesta')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('observacion_admin', models.TextField(blank=True, help_text='Comentario del director al aprobar o rechazar', verbose_name='Observación del director')),
                ('fecha_propuesta', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_actividad_propuesta', models.DateField(blank=True, null=True, verbose_name='Fecha propuesta para la actividad')),
                ('propuesta_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas', to=settings.AUTH_USER_MODEL, verbose_name='Propuesto por')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
            ],
            options={
                'verbose_name': 'Propuesta de Actividad',
                'verbose_name_plural': 'Propuestas de Actividades',
                'ordering': ['-fecha_propuesta'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=300, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('de_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL, verbose_name='De')),
                ('para_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Para')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de excursión')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('num_estudiantes', models.IntegerField(default=0, verbose_name='N° de estudiantes')),
                ('costo_por_alumno', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Costo por alumno (S/)')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='programada', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excursiones', to='core.destino', verbose_name='Destino')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excursiones_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Docente responsable')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excursiones', to='core.seccion', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Excursión',
                'verbose_name_plural': 'Excursiones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='evidencias/%Y/%m/', verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, max_length=500, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='core.actividadinstitucional', verbose_name='Actividad')),
                ('excursion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='core.excursion', verbose_name='Excursión')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_subidas', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('es_urgente', models.BooleanField(default=False, verbose_name='¿Es urgente?')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('destinatarios', models.ManyToManyField(blank=True, help_text='Si está vacío, el aviso es para todos.', related_name='avisos_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Destinatarios específicos')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
