# Generated by Django 4.2.30 on 2026-05-04 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destino',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='excursion',
            name='costo_por_alumno',
        ),
        migrations.AddField(
            model_name='destino',
            name='docente_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinos_referencia', to=settings.AUTH_USER_MODEL, verbose_name='Docente de referencia'),
        ),
    ]
