# Generated by Django 4.2.30 on 2026-06-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_destino_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadinstitucional',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='actividades/', verbose_name='Imagen principal'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='excursiones/', verbose_name='Imagen principal'),
        ),
    ]
