# Generated by Django 4.2.30 on 2026-06-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_actividadinstitucional_imagen_excursion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seccion_asignada',
            field=models.CharField(blank=True, help_text='Ej: 3B, 5A, ED.FISICA', max_length=50, verbose_name='Sección / Grado asignado'),
        ),
    ]
