# Generated by Django 4.2.30 on 2026-06-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_seccion_asignada'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='aula',
            field=models.CharField(blank=True, help_text='Ej: 3°A, Aula 5, Primaria 2', max_length=50, verbose_name='Aula'),
        ),
    ]
