# Generated by Django 4.2.30 on 2026-06-16 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_aula_excursion'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='destino_nombre',
            field=models.CharField(blank=True, help_text='Ej: Parque, Museo, Lago Titicaca', max_length=200, verbose_name='Destino'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='grado',
            field=models.CharField(blank=True, help_text='Ej: 3er Grado, 5to Primaria', max_length=100, verbose_name='Grado'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='seccion_nombre',
            field=models.CharField(blank=True, help_text='Ej: 3°A, 5°B', max_length=100, verbose_name='Sección'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excursiones', to='core.destino', verbose_name='Destino (referencia)'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excursiones', to='core.seccion', verbose_name='Sección (referencia)'),
        ),
    ]
