# Generated by Django 4.2.30 on 2026-06-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_excursion_destino_nombre_excursion_grado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='grado_seccion',
            field=models.CharField(blank=True, help_text='Ej: 3er Grado "A", 5to Primaria "B"', max_length=200, verbose_name='Grado y Sección'),
        ),
    ]
